// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp3o933sixzx1qsGQNW_KdOXN_5NBX9XY',
    appId: '1:195091699687:web:5adb8f9ce01a674c468f42',
    messagingSenderId: '195091699687',
    projectId: 'byte-todo',
    authDomain: 'byte-todo.firebaseapp.com',
    storageBucket: 'byte-todo.firebasestorage.app',
    measurementId: 'G-PTSG5ZNESS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzcEtlBlzp__1OPmMz_ITEYUEgRPpeDE',
    appId: '1:195091699687:ios:7b6aff0930039a73468f42',
    messagingSenderId: '195091699687',
    projectId: 'byte-todo',
    storageBucket: 'byte-todo.firebasestorage.app',
    iosBundleId: 'com.example.byteTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzcEtlBlzp__1OPmMz_ITEYUEgRPpeDE',
    appId: '1:195091699687:ios:7b6aff0930039a73468f42',
    messagingSenderId: '195091699687',
    projectId: 'byte-todo',
    storageBucket: 'byte-todo.firebasestorage.app',
    iosBundleId: 'com.example.byteTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp3o933sixzx1qsGQNW_KdOXN_5NBX9XY',
    appId: '1:195091699687:web:5ad385e6e82fa9c6468f42',
    messagingSenderId: '195091699687',
    projectId: 'byte-todo',
    authDomain: 'byte-todo.firebaseapp.com',
    storageBucket: 'byte-todo.firebasestorage.app',
    measurementId: 'G-TYB4F468PG',
  );
}
